-- Generated from data/seed-names.ts — do not edit by hand.
insert into public.names (name, gender, origin, meaning) values
  ('Aurora', 'girl', 'Latin', 'Dawn'),
  ('Amelia', 'girl', 'Germanic', 'Work'),
  ('Ava', 'girl', 'Latin', 'Bird, life'),
  ('Astrid', 'girl', 'Scandinavian', 'Divinely beautiful'),
  ('Adelaide', 'girl', 'Germanic', 'Noble kind'),
  ('Adeline', 'girl', 'Germanic', 'Noble'),
  ('Aisling', 'girl', 'Irish', 'Dream, vision'),
  ('Alba', 'girl', 'Latin', 'White, dawn'),
  ('Alice', 'girl', 'Germanic', 'Noble'),
  ('Alina', 'girl', 'Slavic', 'Bright, beautiful'),
  ('Alma', 'girl', 'Latin', 'Nourishing soul'),
  ('Althea', 'girl', 'Greek', 'Healer'),
  ('Amaya', 'girl', 'Japanese', 'Night rain'),
  ('Amber', 'girl', 'Arabic', 'Jewel'),
  ('Amelie', 'girl', 'French', 'Hard-working'),
  ('Anastasia', 'girl', 'Greek', 'Resurrection'),
  ('Andrea', 'girl', 'Greek', 'Strong, brave'),
  ('Angelica', 'girl', 'Latin', 'Angelic'),
  ('Annabel', 'girl', 'Latin', 'Loving, graceful'),
  ('Anneliese', 'girl', 'Germanic', 'Grace, God''s promise'),
  ('Annie', 'girl', 'English', 'Grace'),
  ('Antonia', 'girl', 'Latin', 'Priceless'),
  ('Aoife', 'girl', 'Irish', 'Beauty, radiance'),
  ('April', 'girl', 'Latin', 'To open'),
  ('Ariadne', 'girl', 'Greek', 'Most holy'),
  ('Arielle', 'girl', 'Hebrew', 'Lion of God'),
  ('Arietta', 'girl', 'Italian', 'Little melody'),
  ('Ashley', 'girl', 'English', 'Ash tree meadow'),
  ('Athena', 'girl', 'Greek', 'Goddess of wisdom'),
  ('Aubrey', 'girl', 'Germanic', 'Elf ruler'),
  ('Audrey', 'girl', 'English', 'Noble strength'),
  ('Augusta', 'girl', 'Latin', 'Majestic'),
  ('Autumn', 'girl', 'Latin', 'The season'),
  ('Aveline', 'girl', 'French', 'Hazelnut'),
  ('Ayla', 'girl', 'Turkish', 'Moonlight'),
  ('Azalea', 'girl', 'Greek', 'Flower'),
  ('Azura', 'girl', 'Spanish', 'Sky blue'),
  ('Alejandra', 'girl', 'Spanish', 'Defender of men'),
  ('Alondra', 'girl', 'Spanish', 'Lark'),
  ('Altagracia', 'girl', 'Spanish', 'High grace'),
  ('Amada', 'girl', 'Spanish', 'Beloved'),
  ('Amalia', 'girl', 'Spanish', 'Hardworking'),
  ('Amanda', 'girl', 'Latin', 'Worthy of love'),
  ('Amarilis', 'girl', 'Spanish', 'Sparkling flower'),
  ('Ana', 'girl', 'Spanish', 'Grace'),
  ('Anabel', 'girl', 'Spanish', 'Graceful beauty'),
  ('Anaís', 'girl', 'Spanish', 'Grace'),
  ('Araceli', 'girl', 'Spanish', 'Altar of heaven'),
  ('Ariana', 'girl', 'Spanish', 'Most holy'),
  ('Arlene', 'girl', 'Spanish', 'Pledge, promise'),
  ('Asunción', 'girl', 'Spanish', 'Assumption'),
  ('Azucena', 'girl', 'Spanish', 'Madonna lily'),
  ('Beatrice', 'girl', 'Latin', 'She who brings happiness'),
  ('Camila', 'girl', 'Spanish', 'Young ceremonial attendant'),
  ('Charlotte', 'girl', 'French', 'Free one'),
  ('Chloe', 'girl', 'Greek', 'Blooming'),
  ('Clara', 'girl', 'Latin', 'Bright, clear'),
  ('Cora', 'girl', 'Greek', 'Maiden'),
  ('Daisy', 'girl', 'English', 'Day''s eye'),
  ('Delilah', 'girl', 'Hebrew', 'Delicate'),
  ('Eleanor', 'girl', 'Greek', 'Shining light'),
  ('Elena', 'girl', 'Greek', 'Bright, shining light'),
  ('Eliza', 'girl', 'Hebrew', 'Pledged to God'),
  ('Ella', 'girl', 'Germanic', 'All, completely'),
  ('Ellie', 'girl', 'English', 'Light'),
  ('Emma', 'girl', 'Germanic', 'Whole, universal'),
  ('Esme', 'girl', 'French', 'Beloved'),
  ('Evangeline', 'girl', 'Greek', 'Bearer of good news'),
  ('Evelyn', 'girl', 'English', 'Wished-for child'),
  ('Fiona', 'girl', 'Irish', 'Fair, white'),
  ('Freya', 'girl', 'Scandinavian', 'Noble lady'),
  ('Gemma', 'girl', 'Italian', 'Precious stone'),
  ('Genevieve', 'girl', 'French', 'Tribe woman'),
  ('Grace', 'girl', 'Latin', 'Charm, grace'),
  ('Hannah', 'girl', 'Hebrew', 'Grace, favor'),
  ('Harper', 'girl', 'English', 'Harp player'),
  ('Hazel', 'girl', 'English', 'The hazelnut tree'),
  ('Imogen', 'girl', 'Celtic', 'Maiden'),
  ('Iris', 'girl', 'Greek', 'Rainbow'),
  ('Isabella', 'girl', 'Hebrew', 'Devoted to God'),
  ('Isla', 'girl', 'Scottish', 'Island'),
  ('Ivy', 'girl', 'English', 'Faithfulness'),
  ('Jade', 'girl', 'Spanish', 'Stone of the side'),
  ('Josephine', 'girl', 'Hebrew', 'God will add'),
  ('Julia', 'girl', 'Latin', 'Youthful'),
  ('Juniper', 'girl', 'Latin', 'Young'),
  ('Kaia', 'girl', 'Scandinavian', 'Earth'),
  ('Lana', 'girl', 'Slavic', 'Light'),
  ('Layla', 'girl', 'Arabic', 'Night'),
  ('Leah', 'girl', 'Hebrew', 'Weary'),
  ('Lila', 'girl', 'Arabic', 'Night'),
  ('Lily', 'girl', 'English', 'Pure, the flower'),
  ('Lucia', 'girl', 'Latin', 'Light'),
  ('Lucy', 'girl', 'Latin', 'Light'),
  ('Luna', 'girl', 'Latin', 'Moon'),
  ('Maeve', 'girl', 'Irish', 'She who intoxicates'),
  ('Maisie', 'girl', 'Scottish', 'Pearl'),
  ('Margot', 'girl', 'French', 'Pearl'),
  ('Maya', 'girl', 'Sanskrit', 'Illusion, dream'),
  ('Mia', 'girl', 'Italian', 'Mine'),
  ('Mila', 'girl', 'Slavic', 'Gracious, dear'),
  ('Nora', 'girl', 'Irish', 'Light'),
  ('Olivia', 'girl', 'Latin', 'Olive tree'),
  ('Opal', 'girl', 'Sanskrit', 'Jewel'),
  ('Penelope', 'girl', 'Greek', 'Weaver'),
  ('Phoebe', 'girl', 'Greek', 'Radiant, shining'),
  ('Poppy', 'girl', 'English', 'Red flower'),
  ('Rose', 'girl', 'Latin', 'The flower'),
  ('Ruby', 'girl', 'Latin', 'Red gemstone'),
  ('Sadie', 'girl', 'Hebrew', 'Princess'),
  ('Sage', 'girl', 'Latin', 'Wise one'),
  ('Sienna', 'girl', 'Italian', 'Orange-red'),
  ('Sofia', 'girl', 'Greek', 'Wisdom'),
  ('Stella', 'girl', 'Latin', 'Star'),
  ('Tessa', 'girl', 'Greek', 'Harvester'),
  ('Thea', 'girl', 'Greek', 'Goddess'),
  ('Violet', 'girl', 'Latin', 'Purple flower'),
  ('Vivienne', 'girl', 'French', 'Alive'),
  ('Willa', 'girl', 'Germanic', 'Resolute protection'),
  ('Willow', 'girl', 'English', 'Willow tree'),
  ('Wren', 'girl', 'English', 'Small bird'),
  ('Zoe', 'girl', 'Greek', 'Life'),
  ('Amara', 'girl', 'African', 'Grace'),
  ('Anya', 'girl', 'Slavic', 'Grace'),
  ('Noor', 'girl', 'Arabic', 'Light'),
  ('Saoirse', 'girl', 'Irish', 'Freedom'),
  ('Aaliyah', 'girl', 'Arabic', 'Exalted'),
  ('Anika', 'girl', 'Sanskrit', 'Grace'),
  ('Abby', 'girl', 'Hebrew', 'My father is joyful'),
  ('Abigail', 'girl', 'Hebrew', 'My father is joyful'),
  ('Abriella', 'girl', 'Hebrew', 'God is my strength'),
  ('Ada', 'girl', 'Germanic', 'Noble'),
  ('Adalee', 'girl', 'Germanic', 'Noble'),
  ('Adalyn', 'girl', 'Germanic', 'Noble'),
  ('Adara', 'girl', 'Hebrew', 'Noble, exalted'),
  ('Addison', 'girl', 'English', 'Child of Adam'),
  ('Adley', 'girl', 'Hebrew', 'God is just'),
  ('Adriana', 'girl', 'Latin', 'From Adria'),
  ('Adrienne', 'girl', 'French', 'From Adria'),
  ('Agnes', 'girl', 'Greek', 'Pure, holy'),
  ('Aida', 'girl', 'Arabic', 'Reward, gift'),
  ('Aileen', 'girl', 'Irish', 'Light'),
  ('Ainsley', 'girl', 'Scottish', 'One''s own meadow'),
  ('Aisha', 'girl', 'Arabic', 'Alive, prosperous'),
  ('Alana', 'girl', 'Celtic', 'Little rock'),
  ('Alani', 'girl', 'Hawaiian', 'Orange tree'),
  ('Alara', 'girl', 'Turkish', 'Water fairy'),
  ('Alaya', 'girl', 'Arabic', 'Sublime, high'),
  ('Alicia', 'girl', 'Spanish', 'Noble'),
  ('Alisa', 'girl', 'Hebrew', 'Great happiness'),
  ('Alisha', 'girl', 'Sanskrit', 'Protected by god'),
  ('Alissa', 'girl', 'Germanic', 'Noble'),
  ('Alivia', 'girl', 'Latin', 'Olive tree'),
  ('Aliya', 'girl', 'Arabic', 'Exalted, noble'),
  ('Aliyah', 'girl', 'Arabic', 'Exalted, noble'),
  ('Allie', 'girl', 'English', 'Noble'),
  ('Allison', 'girl', 'Germanic', 'Noble'),
  ('Ally', 'girl', 'English', 'Noble'),
  ('Allyson', 'girl', 'Germanic', 'Noble'),
  ('Alyssa', 'girl', 'Greek', 'Rational'),
  ('Amani', 'girl', 'Swahili', 'Peace, wish'),
  ('Amari', 'girl', 'Hebrew', 'Eternal'),
  ('Amaris', 'girl', 'Hebrew', 'God has promised'),
  ('Amberley', 'girl', 'English', 'Meadow of amber'),
  ('Amberly', 'girl', 'English', 'Meadow of amber'),
  ('Amia', 'girl', 'French', 'Beloved'),
  ('Amie', 'girl', 'French', 'Beloved friend'),
  ('Amiyah', 'girl', 'Hebrew', 'Close to God'),
  ('Amy', 'girl', 'French', 'Beloved'),
  ('Andromeda', 'girl', 'Greek', 'Ruler of men'),
  ('Angel', 'girl', 'Latin', 'Messenger of God'),
  ('Angela', 'girl', 'Latin', 'Angel'),
  ('Angelina', 'girl', 'Latin', 'Angel'),
  ('Angeline', 'girl', 'French', 'Angel'),
  ('Aniyah', 'girl', 'Hebrew', 'God answers'),
  ('Anna', 'girl', 'Latin', 'Grace'),
  ('Annalise', 'girl', 'Germanic', 'Grace and oath'),
  ('Anne', 'girl', 'Hebrew', 'Grace'),
  ('Annelise', 'girl', 'Germanic', 'Grace and oath'),
  ('Annora', 'girl', 'Latin', 'Honor'),
  ('Arabella', 'girl', 'Latin', 'Yielding to prayer'),
  ('Areli', 'girl', 'Hebrew', 'Lion of God'),
  ('Arely', 'girl', 'Hebrew', 'Lion of God'),
  ('Aria', 'girl', 'Italian', 'Air, melody'),
  ('Ariel', 'girl', 'Hebrew', 'Lion of God'),
  ('Ariella', 'girl', 'Hebrew', 'Lion of God'),
  ('Aris', 'girl', 'Greek', 'Best'),
  ('Arissa', 'girl', 'Greek', 'Best'),
  ('Ariya', 'girl', 'Sanskrit', 'Noble'),
  ('Arleth', 'girl', 'Germanic', 'Eagle'),
  ('Armelle', 'girl', 'Celtic', 'Stone princess'),
  ('Arya', 'girl', 'Sanskrit', 'Noble, honorable'),
  ('Asha', 'girl', 'Sanskrit', 'Hope, wish'),
  ('Ashlee', 'girl', 'English', 'Ash tree meadow'),
  ('Ashleigh', 'girl', 'English', 'Ash tree meadow'),
  ('Ashlyn', 'girl', 'English', 'Ash tree pool'),
  ('Ashlynn', 'girl', 'English', 'Ash tree pool'),
  ('Asia', 'girl', 'Greek', 'Sunrise'),
  ('Aspen', 'girl', 'English', 'Quaking tree'),
  ('Asteria', 'girl', 'Greek', 'Star'),
  ('Aubree', 'girl', 'French', 'Elf ruler'),
  ('Audra', 'girl', 'English', 'Noble strength'),
  ('Aurélie', 'girl', 'French', 'Golden'),
  ('Austyn', 'girl', 'Latin', 'Majestic'),
  ('Avalon', 'girl', 'Celtic', 'Island of apples'),
  ('Avari', 'girl', 'English', 'From the sky'),
  ('Aviana', 'girl', 'Latin', 'Bird'),
  ('Avianna', 'girl', 'Latin', 'Bird like'),
  ('Avonlea', 'girl', 'English', 'River of Avon'),
  ('Axelle', 'girl', 'Hebrew', 'Father of peace'),
  ('Ayanna', 'girl', 'Native American', 'Eternal blossom'),
  ('Aylin', 'girl', 'Turkish', 'Moon halo'),
  ('Abrianna', 'girl', 'Hebrew', 'Mother of multitudes'),
  ('Acacia', 'girl', 'Greek', 'Thorny tree'),
  ('Adamaris', 'girl', 'Latin', 'Noble, of the sea'),
  ('Adria', 'girl', 'Latin', 'From Adria'),
  ('Adrina', 'girl', 'Greek', 'Happiness'),
  ('Aeryn', 'girl', 'Irish', 'Ireland'),
  ('Afton', 'girl', 'English', 'From the Afton river'),
  ('Agate', 'girl', 'French', 'Good woman'),
  ('Agave', 'girl', 'Greek', 'Illustrious'),
  ('Agni', 'girl', 'Sanskrit', 'Fire'),
  ('Ahanu', 'girl', 'Native American', 'He laughs'),
  ('Aiko', 'girl', 'Japanese', 'Love child'),
  ('Aina', 'girl', 'Scandinavian', 'Grace'),
  ('Aimy', 'girl', 'French', 'Beloved'),
  ('Aine', 'girl', 'Irish', 'Radiance, brightness'),
  ('Aiyana', 'girl', 'Native American', 'Eternal blossom'),
  ('Akosua', 'girl', 'Akan', 'Born on Sunday'),
  ('Alaia', 'girl', 'Basque', 'Joyful, happy'),
  ('Alanis', 'girl', 'Celtic', 'Little rock'),
  ('Agustina', 'girl', 'Spanish', 'Majestic'),
  ('Aidalys', 'girl', 'Spanish', 'Gift of God'),
  ('Ailen', 'girl', 'Spanish', 'Light'),
  ('Ainara', 'girl', 'Basque', 'Swallow bird'),
  ('Aixa', 'girl', 'Arabic', 'Alive'),
  ('Aleja', 'girl', 'Spanish', 'Defender'),
  ('Alexa', 'girl', 'Spanish', 'Defender of men'),
  ('Alexandra', 'girl', 'Spanish', 'Defender of men'),
  ('Alexia', 'girl', 'Spanish', 'Defender'),
  ('Alexis', 'girl', 'Spanish', 'Defender'),
  ('Alisson', 'girl', 'Spanish', 'Noble'),
  ('Almudena', 'girl', 'Spanish', 'Our Lady'),
  ('Ambar', 'girl', 'Spanish', 'Jewel'),
  ('Amparo', 'girl', 'Spanish', 'Shelter, refuge'),
  ('Amparito', 'girl', 'Spanish', 'Little shelter'),
  ('Anahí', 'girl', 'Guaraní', 'Ceibo flower'),
  ('Analía', 'girl', 'Spanish', 'Grace'),
  ('Analiz', 'girl', 'Spanish', 'Grace'),
  ('Analucia', 'girl', 'Spanish', 'Graceful light'),
  ('Anayansi', 'girl', 'Spanish', 'Blessing'),
  ('Angie', 'girl', 'Spanish', 'Angel'),
  ('Angélica', 'girl', 'Spanish', 'Angelic'),
  ('Aniela', 'girl', 'Spanish', 'Grace'),
  ('Anixa', 'girl', 'Spanish', 'Grace'),
  ('Antonella', 'girl', 'Spanish', 'Priceless'),
  ('Antonette', 'girl', 'Spanish', 'Priceless'),
  ('Aracely', 'girl', 'Spanish', 'Altar of heaven'),
  ('Arcelia', 'girl', 'Spanish', 'Treasure'),
  ('Argelia', 'girl', 'Spanish', 'From Algeria'),
  ('Argentina', 'girl', 'Spanish', 'Silvery'),
  ('Ariadna', 'girl', 'Spanish', 'Most holy'),
  ('Arianny', 'girl', 'Spanish', 'Silver'),
  ('Arisleidy', 'girl', 'Spanish', 'Noble'),
  ('Arizbe', 'girl', 'Spanish', 'Princess'),
  ('Arlenis', 'girl', 'Spanish', 'Pledge'),
  ('Arlette', 'girl', 'Spanish', 'Eagle'),
  ('Armida', 'girl', 'Spanish', 'Armed'),
  ('Arnelia', 'girl', 'Spanish', 'Eagle'),
  ('Aurelia', 'girl', 'Spanish', 'Golden'),
  ('Avelina', 'girl', 'Spanish', 'Hazelnut'),
  ('Ayleen', 'girl', 'Spanish', 'Light'),
  ('Aymara', 'girl', 'Spanish', 'Free spirit'),
  ('Azahara', 'girl', 'Arabic', 'Flower, blossom'),
  ('Azeneth', 'girl', 'Spanish', 'Gift of God'),
  ('Suri', 'girl', 'Hebrew', 'Princess'),
  ('Yuki', 'girl', 'Japanese', 'Snow'),
  ('Sakura', 'girl', 'Japanese', 'Cherry blossom'),
  ('Kira', 'girl', 'Japanese', 'Glitter, shine'),
  ('Aaron', 'boy', 'Hebrew', 'Exalted, strong'),
  ('Adrian', 'boy', 'Latin', 'Son of Adria'),
  ('Alexander', 'boy', 'Greek', 'Defender of men'),
  ('Arlo', 'boy', 'Old English', 'Fortified hill'),
  ('Asher', 'boy', 'Hebrew', 'Happy, blessed'),
  ('Atlas', 'boy', 'Greek', 'To carry, endure'),
  ('August', 'boy', 'Latin', 'Great, magnificent'),
  ('Austin', 'boy', 'Latin', 'Majestic dignity'),
  ('Axel', 'boy', 'Scandinavian', 'Father of peace'),
  ('Alec', 'boy', 'Scottish', 'Defender of men'),
  ('Alejandro', 'boy', 'Spanish', 'Defender of men'),
  ('Alessio', 'boy', 'Italian', 'Defender'),
  ('Alfie', 'boy', 'English', 'Wise counsel'),
  ('Alfred', 'boy', 'English', 'Wise counsel'),
  ('Ali', 'boy', 'Arabic', 'Exalted'),
  ('Alistair', 'boy', 'Scottish', 'Defender of men'),
  ('Alonzo', 'boy', 'Spanish', 'Noble, eager'),
  ('Ambrose', 'boy', 'Greek', 'Immortal'),
  ('Amir', 'boy', 'Arabic', 'Prince'),
  ('Amos', 'boy', 'Hebrew', 'Carried by God'),
  ('Anders', 'boy', 'Scandinavian', 'Strong, brave'),
  ('Andre', 'boy', 'French', 'Manly'),
  ('Andrew', 'boy', 'Greek', 'Strong, brave'),
  ('Angelo', 'boy', 'Italian', 'Angel'),
  ('Ansel', 'boy', 'Germanic', 'Protected by God'),
  ('Anthony', 'boy', 'Latin', 'Priceless'),
  ('Apollo', 'boy', 'Greek', 'God of light'),
  ('Archer', 'boy', 'English', 'Bowman'),
  ('Archie', 'boy', 'English', 'Genuine, bold'),
  ('Ari', 'boy', 'Hebrew', 'Lion'),
  ('Arjun', 'boy', 'Sanskrit', 'Bright, shining'),
  ('Armand', 'boy', 'French', 'Soldier'),
  ('Arthur', 'boy', 'Celtic', 'Bear'),
  ('Arturo', 'boy', 'Italian', 'Bear'),
  ('Atticus', 'boy', 'Greek', 'From Attica'),
  ('Avi', 'boy', 'Hebrew', 'My father'),
  ('Abel', 'boy', 'Spanish', 'Breath, son'),
  ('Adalberto', 'boy', 'Spanish', 'Noble, bright'),
  ('Adán', 'boy', 'Spanish', 'Man, earth'),
  ('Agustín', 'boy', 'Spanish', 'Majestic'),
  ('Alberto', 'boy', 'Spanish', 'Noble, bright'),
  ('Alfonso', 'boy', 'Spanish', 'Noble, ready'),
  ('Alfredo', 'boy', 'Spanish', 'Wise counsel'),
  ('Aníbal', 'boy', 'Spanish', 'Grace of Baal'),
  ('Antonio', 'boy', 'Spanish', 'Priceless'),
  ('Arcadio', 'boy', 'Spanish', 'From Arcadia'),
  ('Argenis', 'boy', 'Spanish', 'Silvery'),
  ('Armando', 'boy', 'Spanish', 'Soldier'),
  ('Arnaldo', 'boy', 'Spanish', 'Eagle ruler'),
  ('Asael', 'boy', 'Spanish', 'God has made'),
  ('Aurelio', 'boy', 'Spanish', 'Golden'),
  ('Beckett', 'boy', 'English', 'Bee cottage, stream'),
  ('Benjamin', 'boy', 'Hebrew', 'Son of the right hand'),
  ('Bodhi', 'boy', 'Sanskrit', 'Awakening, enlightenment'),
  ('Caleb', 'boy', 'Hebrew', 'Whole-hearted'),
  ('Callum', 'boy', 'Scottish', 'Dove'),
  ('Cameron', 'boy', 'Scottish', 'Crooked nose'),
  ('Charlie', 'boy', 'English', 'Free one'),
  ('Cillian', 'boy', 'Irish', 'War, strife'),
  ('Cole', 'boy', 'English', 'Coal, dark'),
  ('Conor', 'boy', 'Irish', 'Lover of hounds'),
  ('Cyrus', 'boy', 'Persian', 'Sun'),
  ('Daniel', 'boy', 'Hebrew', 'God is my judge'),
  ('Declan', 'boy', 'Irish', 'Man of prayer'),
  ('Desmond', 'boy', 'Irish', 'From South Munster'),
  ('Dominic', 'boy', 'Latin', 'Belonging to the Lord'),
  ('Eden', 'boy', 'Hebrew', 'Place of pleasure'),
  ('Edward', 'boy', 'English', 'Wealthy guardian'),
  ('Eli', 'boy', 'Hebrew', 'Ascended, uplifted'),
  ('Elias', 'boy', 'Hebrew', 'The Lord is my God'),
  ('Ellis', 'boy', 'Welsh', 'Benevolent'),
  ('Emilio', 'boy', 'Italian', 'Rival'),
  ('Emmett', 'boy', 'Germanic', 'Universal, truth'),
  ('Ethan', 'boy', 'Hebrew', 'Strong, enduring'),
  ('Ezra', 'boy', 'Hebrew', 'Helper'),
  ('Felix', 'boy', 'Latin', 'Happy, fortunate'),
  ('Finn', 'boy', 'Irish', 'Fair'),
  ('Finley', 'boy', 'Scottish', 'Fair-haired hero'),
  ('Gabriel', 'boy', 'Hebrew', 'God is my strength'),
  ('George', 'boy', 'Greek', 'Farmer, earth-worker'),
  ('Graham', 'boy', 'English', 'Gravelly homestead'),
  ('Grayson', 'boy', 'English', 'Son of the steward'),
  ('Gus', 'boy', 'Latin', 'Great'),
  ('Harrison', 'boy', 'English', 'Son of Harry'),
  ('Henry', 'boy', 'Germanic', 'Ruler of the home'),
  ('Holden', 'boy', 'English', 'Hollow valley'),
  ('Hudson', 'boy', 'English', 'Son of Hugh'),
  ('Hugo', 'boy', 'Germanic', 'Mind, intellect'),
  ('Ian', 'boy', 'Scottish', 'God is gracious'),
  ('Isaac', 'boy', 'Hebrew', 'He will laugh'),
  ('Jack', 'boy', 'English', 'God is gracious'),
  ('James', 'boy', 'Hebrew', 'Supplanter'),
  ('Jasper', 'boy', 'Persian', 'Treasurer'),
  ('Julian', 'boy', 'Latin', 'Youthful'),
  ('Kai', 'boy', 'Hawaiian', 'Sea'),
  ('Kieran', 'boy', 'Irish', 'Little dark one'),
  ('Leo', 'boy', 'Latin', 'Lion'),
  ('Levi', 'boy', 'Hebrew', 'Joined, attached'),
  ('Liam', 'boy', 'Irish', 'Strong-willed warrior'),
  ('Lincoln', 'boy', 'English', 'Lake settlement'),
  ('Lucas', 'boy', 'Latin', 'Light'),
  ('Luka', 'boy', 'Slavic', 'From Lucania'),
  ('Mateo', 'boy', 'Spanish', 'Gift of God'),
  ('Matthias', 'boy', 'Hebrew', 'Gift of God'),
  ('Maverick', 'boy', 'English', 'Independent'),
  ('Max', 'boy', 'Latin', 'Greatest'),
  ('Micah', 'boy', 'Hebrew', 'Who is like God'),
  ('Miles', 'boy', 'Latin', 'Soldier, merciful'),
  ('Milo', 'boy', 'Germanic', 'Soldier, merciful'),
  ('Nathan', 'boy', 'Hebrew', 'He gave'),
  ('Noah', 'boy', 'Hebrew', 'Rest, comfort'),
  ('Oliver', 'boy', 'Latin', 'Olive tree'),
  ('Orion', 'boy', 'Greek', 'Son of fire, hunter'),
  ('Oscar', 'boy', 'Irish', 'Deer-lover, friend'),
  ('Owen', 'boy', 'Welsh', 'Young warrior'),
  ('Patrick', 'boy', 'Latin', 'Noble'),
  ('Peter', 'boy', 'Greek', 'Rock'),
  ('Rafael', 'boy', 'Hebrew', 'God has healed'),
  ('Ronan', 'boy', 'Irish', 'Little seal'),
  ('Rowan', 'boy', 'Irish', 'Little red-haired one'),
  ('Ryder', 'boy', 'English', 'Horseman'),
  ('Samuel', 'boy', 'Hebrew', 'Heard by God'),
  ('Sebastian', 'boy', 'Greek', 'Venerable'),
  ('Silas', 'boy', 'Latin', 'Of the forest'),
  ('Soren', 'boy', 'Scandinavian', 'Stern'),
  ('Theo', 'boy', 'Greek', 'Gift of God'),
  ('Theodore', 'boy', 'Greek', 'Gift of God'),
  ('Thomas', 'boy', 'Aramaic', 'Twin'),
  ('Tobias', 'boy', 'Hebrew', 'God is good'),
  ('Wesley', 'boy', 'English', 'Western meadow'),
  ('William', 'boy', 'Germanic', 'Resolute protector'),
  ('Xavier', 'boy', 'Basque', 'New house'),
  ('Zayd', 'boy', 'Arabic', 'Abundance'),
  ('Haruki', 'boy', 'Japanese', 'Shining'),
  ('Ren', 'boy', 'Japanese', 'Lotus'),
  ('Kenji', 'boy', 'Japanese', 'Strong, vigorous'),
  ('Idris', 'boy', 'Welsh', 'Ardent lord'),
  ('Malachi', 'boy', 'Hebrew', 'My messenger'),
  ('Avery', 'unisex', 'English', 'Ruler of elves'),
  ('Ainsley', 'unisex', 'Scottish', 'One''s own meadow'),
  ('Alex', 'unisex', 'Greek', 'Defender of men'),
  ('Ariel', 'unisex', 'Hebrew', 'Lion of God'),
  ('Ash', 'unisex', 'English', 'Ash tree'),
  ('Aspen', 'unisex', 'English', 'Quaking tree'),
  ('Auden', 'unisex', 'English', 'Old friend'),
  ('Blake', 'unisex', 'English', 'Fair-haired'),
  ('Cameron', 'unisex', 'Scottish', 'Crooked nose'),
  ('Casey', 'unisex', 'Irish', 'Brave in battle'),
  ('Dakota', 'unisex', 'Native American', 'Friend, ally'),
  ('Elliot', 'unisex', 'Hebrew', 'The Lord is my God'),
  ('Emerson', 'unisex', 'English', 'Brave, powerful'),
  ('Finley', 'unisex', 'Scottish', 'Fair-haired hero'),
  ('Hayden', 'unisex', 'English', 'Heather-grown hill'),
  ('Jordan', 'unisex', 'Hebrew', 'To flow down'),
  ('Juno', 'unisex', 'Latin', 'Queen of heaven'),
  ('Kai', 'unisex', 'Hawaiian', 'Sea'),
  ('Lennon', 'unisex', 'Irish', 'Little cloak'),
  ('Logan', 'unisex', 'Scottish', 'Little hollow'),
  ('Morgan', 'unisex', 'Welsh', 'Sea-born'),
  ('Parker', 'unisex', 'English', 'Park keeper'),
  ('Phoenix', 'unisex', 'Greek', 'Rising bird'),
  ('Quinn', 'unisex', 'Irish', 'Wise, intelligent'),
  ('Reese', 'unisex', 'Welsh', 'Enthusiasm'),
  ('Remy', 'unisex', 'French', 'Oarsman'),
  ('River', 'unisex', 'English', 'Flowing body of water'),
  ('Robin', 'unisex', 'English', 'Bright fame'),
  ('Rowan', 'unisex', 'Irish', 'Little red-haired one'),
  ('Sage', 'unisex', 'Latin', 'Wise one'),
  ('Sawyer', 'unisex', 'English', 'Woodcutter'),
  ('Skyler', 'unisex', 'Dutch', 'Scholar'),
  ('Sloan', 'unisex', 'Irish', 'Raider'),
  ('Tatum', 'unisex', 'English', 'Cheerful bringer of joy'),
  ('Wren', 'unisex', 'English', 'Small bird')
on conflict (name, gender) do nothing;
