-- A-name expansion: inserts every row from seed.sql whose name starts with "A".
-- Safe to re-run: existing (name, gender) pairs are ignored via ON CONFLICT.
insert into public.names (name, gender, origin, meaning) values
  ('Aurora', 'girl', 'Latin', 'Dawn'),
  ('Amelia', 'girl', 'Germanic', 'Work'),
  ('Ava', 'girl', 'Latin', 'Bird, life'),
  ('Astrid', 'girl', 'Scandinavian', 'Divinely beautiful'),
  ('Adelaide', 'girl', 'Germanic', 'Noble kind'),
  ('Adeline', 'girl', 'Germanic', 'Noble'),
  ('Aisling', 'girl', 'Irish', 'Dream, vision'),
  ('Alba', 'girl', 'Latin', 'White, dawn'),
  ('Alice', 'girl', 'Germanic', 'Noble'),
  ('Alina', 'girl', 'Slavic', 'Bright, beautiful'),
  ('Alma', 'girl', 'Latin', 'Nourishing soul'),
  ('Althea', 'girl', 'Greek', 'Healer'),
  ('Amaya', 'girl', 'Japanese', 'Night rain'),
  ('Amber', 'girl', 'Arabic', 'Jewel'),
  ('Amelie', 'girl', 'French', 'Hard-working'),
  ('Anastasia', 'girl', 'Greek', 'Resurrection'),
  ('Andrea', 'girl', 'Greek', 'Strong, brave'),
  ('Angelica', 'girl', 'Latin', 'Angelic'),
  ('Annabel', 'girl', 'Latin', 'Loving, graceful'),
  ('Anneliese', 'girl', 'Germanic', 'Grace, God''s promise'),
  ('Annie', 'girl', 'English', 'Grace'),
  ('Antonia', 'girl', 'Latin', 'Priceless'),
  ('Aoife', 'girl', 'Irish', 'Beauty, radiance'),
  ('April', 'girl', 'Latin', 'To open'),
  ('Ariadne', 'girl', 'Greek', 'Most holy'),
  ('Arielle', 'girl', 'Hebrew', 'Lion of God'),
  ('Arietta', 'girl', 'Italian', 'Little melody'),
  ('Ashley', 'girl', 'English', 'Ash tree meadow'),
  ('Athena', 'girl', 'Greek', 'Goddess of wisdom'),
  ('Aubrey', 'girl', 'Germanic', 'Elf ruler'),
  ('Audrey', 'girl', 'English', 'Noble strength'),
  ('Augusta', 'girl', 'Latin', 'Majestic'),
  ('Autumn', 'girl', 'Latin', 'The season'),
  ('Aveline', 'girl', 'French', 'Hazelnut'),
  ('Ayla', 'girl', 'Turkish', 'Moonlight'),
  ('Azalea', 'girl', 'Greek', 'Flower'),
  ('Azura', 'girl', 'Spanish', 'Sky blue'),
  ('Amara', 'girl', 'African', 'Grace'),
  ('Anya', 'girl', 'Slavic', 'Grace'),
  ('Aaliyah', 'girl', 'Arabic', 'Exalted'),
  ('Anika', 'girl', 'Sanskrit', 'Grace'),
  ('Aaron', 'boy', 'Hebrew', 'Exalted, strong'),
  ('Adrian', 'boy', 'Latin', 'Son of Adria'),
  ('Alexander', 'boy', 'Greek', 'Defender of men'),
  ('Arlo', 'boy', 'Old English', 'Fortified hill'),
  ('Asher', 'boy', 'Hebrew', 'Happy, blessed'),
  ('Atlas', 'boy', 'Greek', 'To carry, endure'),
  ('August', 'boy', 'Latin', 'Great, magnificent'),
  ('Austin', 'boy', 'Latin', 'Majestic dignity'),
  ('Axel', 'boy', 'Scandinavian', 'Father of peace'),
  ('Alec', 'boy', 'Scottish', 'Defender of men'),
  ('Alejandro', 'boy', 'Spanish', 'Defender of men'),
  ('Alessio', 'boy', 'Italian', 'Defender'),
  ('Alfie', 'boy', 'English', 'Wise counsel'),
  ('Alfred', 'boy', 'English', 'Wise counsel'),
  ('Ali', 'boy', 'Arabic', 'Exalted'),
  ('Alistair', 'boy', 'Scottish', 'Defender of men'),
  ('Alonzo', 'boy', 'Spanish', 'Noble, eager'),
  ('Ambrose', 'boy', 'Greek', 'Immortal'),
  ('Amir', 'boy', 'Arabic', 'Prince'),
  ('Amos', 'boy', 'Hebrew', 'Carried by God'),
  ('Anders', 'boy', 'Scandinavian', 'Strong, brave'),
  ('Andre', 'boy', 'French', 'Manly'),
  ('Andrew', 'boy', 'Greek', 'Strong, brave'),
  ('Angelo', 'boy', 'Italian', 'Angel'),
  ('Ansel', 'boy', 'Germanic', 'Protected by God'),
  ('Anthony', 'boy', 'Latin', 'Priceless'),
  ('Apollo', 'boy', 'Greek', 'God of light'),
  ('Archer', 'boy', 'English', 'Bowman'),
  ('Archie', 'boy', 'English', 'Genuine, bold'),
  ('Ari', 'boy', 'Hebrew', 'Lion'),
  ('Arjun', 'boy', 'Sanskrit', 'Bright, shining'),
  ('Armand', 'boy', 'French', 'Soldier'),
  ('Arthur', 'boy', 'Celtic', 'Bear'),
  ('Arturo', 'boy', 'Italian', 'Bear'),
  ('Atticus', 'boy', 'Greek', 'From Attica'),
  ('Avi', 'boy', 'Hebrew', 'My father'),
  ('Avery', 'unisex', 'English', 'Ruler of elves'),
  ('Ainsley', 'unisex', 'Scottish', 'One''s own meadow'),
  ('Alex', 'unisex', 'Greek', 'Defender of men'),
  ('Ariel', 'unisex', 'Hebrew', 'Lion of God'),
  ('Ash', 'unisex', 'English', 'Ash tree'),
  ('Aspen', 'unisex', 'English', 'Quaking tree'),
  ('Auden', 'unisex', 'English', 'Old friend')
on conflict (name, gender) do nothing;
